env:
  browser: true
  es2020: true
extends:
  - google
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules: {
  indent: ["error", 4],
  max-len: [2, 150],
  object-curly-spacing: [2, "always"],
  linebreak-style: "off"
}
